### PR TITLE
V2 Fix Integer encode/decode issues on 32-bit platforms.

### PR DESCRIPTION
**Pull request by velichkov**
This is a continuation of pull request #1. It's still work in progress

### CODE REVIEW

**Comment by velichkov** [comment]
Hi @mouse07410,

In 672e852 again I reverted parts of 589244c3.  The `long long` type in skeletons/NativeInteger.c is needed only when calling `asn_INTEGER2(u)long` functions otherwise we could use `long`.

I've added tests that specifically cover the longer constrains in 0888b6c and they succeed on both 64 and 32 bit platforms. The constrains limit now is 63 bit on both platforms because the `asn1c_integer_t` is defined as `intmax_t` in `libasn1parser/asn1parser.h` and it doesn't work with `uintmax_t`

I've also fixed the incorrect range bits reported in https://github.com/vlm/asn1c/pull/129#issuecomment-286431676

**Comment by mouse07410** [comment]
@velichkov in case you did not see:

https://github.com/mouse07410/asn1c/pull/1#issuecomment-288578982 - UPER encoding/decoding with wider constraints seems to work fine.

https://github.com/mouse07410/asn1c/pull/1#issuecomment-288595502 - APER decoding with sider constraints seems to continue to fail. Maybe you know how to address that...?

**Comment by mouse07410** [comment]
@velichkov I know it is not fair - but it looks like I have to make the 115 branch the new master (because there will be no support for vlm/#129 PR).

Could you please submit this code as a new PR against my 115 branch?

Thank you!

**Comment by mouse07410** [comment]
@velichkov I desperately need your help.

I've merged as much of your PRs as I could. In general, things seem to work, including those that were broken.

However, in the process several tests in `asn1c/tests` got broken. I would *greatly* appreciate if you could take a look at the current branch 115 (which has most of your code merged), and create a PR to fix the falling tests:
- `check-src/check-41.c`
- `check-src/check-60.c`
- `check-src/check-62.c`
- `check-src/check-70.c`

Also, please feel free to re-add tests you added in #4.  

I'm attaching the current `asn1c/tests/test-suite.log`:
[test-suite.log.txt](https://github.com/mouse07410/asn1c/files/874462/test-suite.log.txt)

Thank you in advance for your help!

**Pull request merged**
