### PR TITLE
Fix https://github.com/vlm/asn1c/issues/379

### PR DESCRIPTION
**Pull request by robstradling**

### CODE REVIEW

**Comment by robstradling** [comment]
I've just tested mouse07410/asn1c@vlm_master both with and without this PR.  It exhibits the same behaviour as vlm/asn1c@master: without it, the application gets into an infinite loop (and has to be `kill -9`'d); with it, there's no infinite loop.

**Comment by mouse07410** [comment]
I do not know why the Travis CI is not shown on this page. So, while I'm struggling to make it directly visible, you can look at the problems directly on the Travis.org web site.  

Here https://travis-ci.org/github/mouse07410/asn1c/builds/703938374 you should see how Travis CI fails. Hopefully you can figure what's wrong, and how to make it right. 

Thanks

**Comment by mouse07410** [comment]
Also, what happens on your platform when you run `make check` on my fork before and after your patch? *Be warned - it can take 15-30 minutes.*

**Comment by mouse07410** [comment]
### Update

@robstradling at the beginning of this PR/page (and actually against each individual commit) there will be a CI check-box. And now you can see more details at the bottom of the page - right above the "Merge pull request" button block.

**Comment by mouse07410** [comment]
@robstradling 
Screen Shot 2020-07-06 at 09 43 30

**Comment by mouse07410** [comment]
@velichkov, @brchiu, could you please help figuring out why the CI is failing here, but not upstream? This is an important fix, and I'd rather got it in as soon as practically possible.

**Comment by robstradling** [comment]
@mouse07410 There was a follow-on commit upstream, which seems to relate to tests: https://github.com/vlm/asn1c/commit/46b394dd3e382b2b360439ece9621972d79e4f57
I'll add that commit to this PR and we'll see if the CI stops failing.

**Comment by mouse07410** [comment]
@robstradling thank you - it looks like that follow-up commit will remedy the problem. That wil ensure the merge of this PR, as it addresses an important issue.

Thank you for your efforts!

**Comment by robstradling** [comment]
@mouse07410 CI failed again, apparently because "The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by mouse07410** [comment]
Closed via 8ac149d37e4b65d4 

@robstradling, thanks - merged via the above commit. All the CI passes (don't know why it fails here).

Please feel free to test against this repo to make sure it addresses the problem correctly.

**Comment by mouse07410** [comment]
@robstradling no worries - that's not an important failure. I've merged this PR, and all the CI passed.

Thank you!

**Pull request merged**
