### PR TITLE
Sync PR143 with mouse07410's master

### PR DESCRIPTION
**Pull request by brchiu**
As title.

### CODE REVIEW

**Comment by mouse07410** [comment]
Here's the problem I have with this PR.

The current master compiles and runs `examples/sample.source.PKIX1` just fine:
```
$ ./x509dump sample-Certificate-1.der 
<Certificate>
    <tbsCertificate>
        <version>2</version>
        <serialNumber>44:BE:0C:8B:50:00:24:B4:11:D3:36:30:4B:C0:33:77</serialNumber>
        <signature>
            <algorithm>1.2.840.113549.1.1.5</algorithm>
            <parameters>05 00</parameters>
        </signature>
        <issuer>
            <rdnSequence>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.6</type>
                        <value>13 02 55 53</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.8</type>
                        <value>13 02 55 54</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.7</type>
                        <value>13 0E 53 61 6C 74 20 4C 61 6B 65 20 43 69 74 79</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.10</type>
                        <value>
                            13 15 54 68 65 20 55 53 45 52 54 52 55 53 54 20 
                            4E 65 74 77 6F 72 6B
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.11</type>
                        <value>
                            13 18 68 74 74 70 3A 2F 2F 77 77 77 2E 75 73 65 
                            72 74 72 75 73 74 2E 63 6F 6D
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.3</type>
                        <value>
                            13 22 55 54 4E 2D 55 53 45 52 46 69 72 73 74 2D 
                            4E 65 74 77 6F 72 6B 20 41 70 70 6C 69 63 61 74 
                            69 6F 6E 73
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
            </rdnSequence>
        </issuer>
        <validity>
            <notBefore>
                <utcTime>990709184839Z</utcTime>
            </notBefore>
            <notAfter>
                <utcTime>190709185749Z</utcTime>
            </notAfter>
        </validity>
        <subject>
            <rdnSequence>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.6</type>
                        <value>13 02 55 53</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.8</type>
                        <value>13 02 55 54</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.7</type>
                        <value>13 0E 53 61 6C 74 20 4C 61 6B 65 20 43 69 74 79</value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.10</type>
                        <value>
                            13 15 54 68 65 20 55 53 45 52 54 52 55 53 54 20 
                            4E 65 74 77 6F 72 6B
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.11</type>
                        <value>
                            13 18 68 74 74 70 3A 2F 2F 77 77 77 2E 75 73 65 
                            72 74 72 75 73 74 2E 63 6F 6D
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
                <RelativeDistinguishedName>
                    <AttributeTypeAndValue>
                        <type>2.5.4.3</type>
                        <value>
                            13 22 55 54 4E 2D 55 53 45 52 46 69 72 73 74 2D 
                            4E 65 74 77 6F 72 6B 20 41 70 70 6C 69 63 61 74 
                            69 6F 6E 73
                        </value>
                    </AttributeTypeAndValue>
                </RelativeDistinguishedName>
            </rdnSequence>
        </subject>
        <subjectPublicKeyInfo>
            <algorithm>
                <algorithm>1.2.840.113549.1.1.1</algorithm>
                <parameters>05 00</parameters>
            </algorithm>
            <subjectPublicKey>
                0011000010000010000000010000101000000010100000100000000100000001
                0000000010110011111110111001000110100001111001000011011001010101
                1000010110101100000001100011010001011011101000001001101001011000
                1011001011111000101101010000111100000101011101111000001110101110
                0011001010110001011101101001001001101000111011000010001101001010
                1100100101110110001111111110001110011100101101100011011101111001
                0000001110111001101010110110100110001101000001110010010110110110
                0001100101100111111001001011000000011011000110000111001101100001
                0100101011101000011111101100110111010011001011110110010011100011
                1010011001111100000011001111101000010111100000001010001100001101
                0100011110001001010011110101000101110001001011111110111011111100
                0011111111111001101110000001011010000000100001111000100110010011
                0010010100100000100110100100001110000010011010010010010001110110
                0010100001011001001101011010000100011101110000000111111110000011
                0000011001100100000101100010000000101100110100110100100110100100
                1000010110110100110000000110000101111111010100010000100011111000
                0110100000010101100100011000000011001011101001011101010111101110
                0011101100111010111101001000010000000100010111100110000001011001
                1010011110001100001101000111001011101110101110000111100011000101
                1101000100111011000100100100101001101111011111100110010100100111
                1011100110100100010101011100010110111001011011110100001110100100
                1100010100011101001011001001100111000000010100101010010001111000
                0100110000010101101100110100000010011000000010000110101101000011
                1100011000000001101100000111101001111011111101010110101100011100
                0010001000111111110010111110111111111111101010001101000000111010
                0100101101110110000101011001111011010010110100011100011000101110
                1110001111011011010101110001101100110010101000101011100001101111
                1110100010000110101001100011111101110000101010111110010101110000
                1001001010101011010001000001111001000000010100001111101110011100
                1010001101100010111001000110110001101110101000001100100011011110
                1110001010000000010000101111101011101001001011111110100011001110
                0011001000000100100011110111110010001101101101110001110010100011
                0011010100111100000101011101110110011110110000111010111010010111
                101001010000001000000011000000010000000000000001
            </subjectPublicKey>
        </subjectPublicKeyInfo>
        <extensions>
            <Extension>
                <extnID>2.5.29.15</extnID>
                <extnValue>03 02 01 C6</extnValue>
            </Extension>
            <Extension>
                <extnID>2.5.29.19</extnID>
                <critical><true/></critical>
                <extnValue>30 03 01 01 FF</extnValue>
            </Extension>
            <Extension>
                <extnID>2.5.29.14</extnID>
                <extnValue>
                    04 14 FA 86 C9 DB E0 BA E9 78 F5 4B A8 D6 15 DF 
                    F0 D3 E1 6A 14 3C
                </extnValue>
            </Extension>
            <Extension>
                <extnID>2.5.29.31</extnID>
                <extnValue>
                    30 46 30 44 A0 42 A0 40 86 3E 68 74 74 70 3A 2F 
                    2F 63 72 6C 2E 75 73 65 72 74 72 75 73 74 2E 63 
                    6F 6D 2F 55 54 4E 2D 55 53 45 52 46 69 72 73 74 
                    2D 4E 65 74 77 6F 72 6B 41 70 70 6C 69 63 61 74 
                    69 6F 6E 73 2E 63 72 6C
                </extnValue>
            </Extension>
        </extensions>
    </tbsCertificate>
    <signatureAlgorithm>
        <algorithm>1.2.840.113549.1.1.5</algorithm>
        <parameters>05 00</parameters>
    </signatureAlgorithm>
    <signature>
        1010010011110011001001011100110011010001110101001001000110000011
        0010001011010000110011000011001010101011100110111001011001001110
        0011010010010001010101000010000000100101001101000110000101011111
        0010101000000010000101011110000110001011101010101111111101111101
        0110010001010001110011110000101011111111101111000111110111011000
        0010000101101010011110001100101100101111010100010110111111111000
        0100001000011101001100111011110111101011101101010111101110010100
        1100001111000011101010011010000000101101110111111101000100101001
        0001111100011101111111101000111100111111101110111010100001000101
        0010101001111111110100010110111001010101001001001110001010111011
        0000001011111011001100010011111110111110111010001011110011101100
        0100000000101011111110000000000111010100010101100011100011100100
        1100101001000100100000101011010101100001001000000010000101100111
        0110010111110110111100000000101111100111001101001111100010100101
        1100001010011100101000110101110001000000000111111000010110010011
        1001010100000110110111100100111111010100001001111010100110110110
        1010010111111100000101101100110101110011001100010011111110111000
        0110010100100111110011111101010001010011000110101111000010101100
        0110111010011111010011110000010100001100000000111000000110100111
        1000010000101001110001000101101010111101011001000101011101110010
        1010110100111011110011110011011100011000101001101001100011000110
        1010110100000110101101001101110000001000101000110000010011010101
        0010100110100100100101101001101000010010011001110100101010001100
        0110000001000101100111011111000100100011100110101011000000000000
        1001110001101000101101011001100001010000110100111110111110001110
        0010111010010010011001011011000101001000001111100010000110111110
        0001010100110000001010100000110110110101000011001010001101101011
        0011111110101110011111110101011111110101000111111001011001111100
        1101111101101111110111011000001000110000001011000110010100011011
        0100000001001010110011010110100010111001011100101110110001110001
        0111011011101100010101001000111000011111100001010000110000000001
        0110101011111010101001100011100010101100000111111100010010000100
    </signature>
</Certificate>
$
```

With your PR applied, it fails to parse the provided `sample-Certificate-1.der`:
```
$ ./x509dump sample-Certificate-1.der 
sample-Certificate-1.der: Decode failed past byte 0: Input processing error
$
```

And I do *not* want to "fix" this problem by adding `#define <something> <no_constraints>`. A fix should be a real fix, not a bandaid with unclear consequences.

**Comment by brchiu** [comment]
OK, now I know your concern.

This error is irrelevant to `#define <something> <no_constraints>` and adding this `define` won't solve it neither.

I will look into this error, stay tuned.

**Comment by brchiu** [comment]
Modify sample.makefile.regen to let generated PKIX1's makefile has -DASN_DISABLE_PER_SUPPORT in CFLAGS variable.

Then x509dump will be compiled with PER disabled and solve previous problem.

**Comment by mouse07410** [comment]
> Then x509dump will be compiled with PER disabled and solve previous problem.

This is unnecessary. Now that you explained what the problem appears to be, I will test your PR again (as the previous fault is likely to have been my fault - didn't account for the `-iper` default for `progname`. Now I know better).

**Comment by mouse07410** [comment]
Thank you - as you see, this PR is merged.

P.S. I'd appreciate if you could take a look at https://github.com/vlm/asn1c/pull/129#issuecomment-286685144. It is a problem.

**Comment by mouse07410** [comment]
@brchiu I'm afraid I have bad news. Since @persandstrom is unable to maintain his PR #129 (that appears to have some problems), I may have to switch master to 115 branch of this repo. The implication is - I need a new PR, similar to this one, but against the 115 branch (as it will become the new master, to replace the current one).

Can you do it?

Thanks!

**Comment by brchiu** [comment]
hi, @mouse07410 ,

I have several days off and see your mail just now.  I will prepare it. 

You can switch your master branch to any branch at your solely discretion.
Never mind. I really thank for you to pre-integrate these wonderful features, 
then vlm can merge them without doubt.

Stay tuned !

**Comment by mouse07410** [comment]
> I have several days off and see your mail just now. I will prepare it.

Perfect, and no rush. While the branch 115 is there, please prepare your (new) PR against it.

When you don't see branch 115, but branch 129 appears - then you can work against the master.

Thanks!

P.S. (And of course, work with the latest state of the branches - other merges could happen between now and then :)

**Pull request merged**
