### PR TITLE
Fix Integer encode/decode issues on 32-bit platforms.

### PR DESCRIPTION
**Pull request by velichkov**
Hi @mouse07410,

Currently two test cases are failing on 32-bit platforms and the Travis CI build is failing because of this and because of missing AX_CODE_COVERAGE macro.

Could you enable the Travis CI build for your fork from your Travis CI account?

Thanks

### CODE REVIEW

**Comment by mouse07410** [comment]
@velichkov First of all - thank you! Yes I probably can enable Travis CI, and your 1ae1bb3 seems to make perfect sense.

I have concerns with 40b2e58, because they undo the support for wider constraints. Would you be so kind to check that? At this time I'd rather not apply it...

I'll need to check 728da9b - it appears benign, but I need to make sure.

**Comment by velichkov** [comment]
Hi.
> Update - applied to the master.

Thanks but it seems you haven't applied it correctly because c53987395d0d1e9cb18e219c689c739c1e288058 contains only the changes for .gitignore and not the actual m4 macro. When applying changes please use `git cherry-pick <commit>` or `git am`.
 
>I have concerns with changes made by 40b2e58, because they undo the support for wider constraints. Would you be so kind to check that? At this time I'd rather not apply it... Update. 40b2e58 fights with my 3431f56 of 2016-12-31 that dealt with wider PER constraints.

`test-check-70` fails on **32-bit platforms** which indicates that there are problems in 3431f56

> Update. Your 728da9b is trying to undo my 4e19d9d of 2016-12-15 (that fixed vlm#123). I don't think I want it. Could you explain why you need this change, and why the current code doesn't work for you?

I need it because `test-check-127.-gen-PER`  fails on **32-bit platforms** which indicates that there is a problem with the patch from https://github.com/vlm/asn1c/issues/123#issuecomment-264646299

> Update 2. Would you be able and willing to take a look at this issue vlm#129 (comment)? This is something that really needs to be addressed, IMHO.

I'll give it a try and I'm going to add some test cases for vlm/asn1c#123 and  vlm/asn1c#129

**Comment by mouse07410** [comment]
> Thanks but it seems you haven't applied it correctly...

Right. Remedied by now, I think.

> `test-check-70` fails on 32-bit platforms which indicates that there are problems in 3431f56

OK, I hear you. But I'm reluctant fixing `test-check-70` on 32-bit platform(s) at the cost of breaking wider constraints support. Are there other alternatives that you can see?

> I need it because `test-check-127.-gen-PER` fails on 32-bit platforms which indicates that there is a problem with the patch from https://github.com/vlm/asn1c/issues/123#issuecomment-264646299

Similar to above: I hear you, but don't want to (further) break constraints support. I agree that there may be problems with it, but a correct fix shouldn't just revert the support. Any alternative you see besides reverting to vlm/asn1c of pre-2016-Dec-15?

> I'll give it a try and I'm going to add some test cases for vlm/asn1c#123 and vlm/asn1c#129

Yes **please**! This would be a tremendous help, and very useful for the entire community, IMHO.

**Comment by velichkov** [comment]
Hi @mouse07410,

Here is my second attempt to properly fix test failures on 32-bit platform(s). In the first commit I added few tests for #123 and in the second I reverted part of 0937360 and made several fixes.

What still needs to be done is a fix for `test-check-70` and some test cases for #129

**Comment by mouse07410** [comment]
> What still needs to be done is a fix for test-check-70 and some test cases for #129

Yep. And we'll get the 32-bit tests. I don't think #129 is working as it should, so probably changes are needed anyway. For example, this:
```
Test DEFINITIONS ::= BEGIN

Test ::= SEQUENCE 
{
	varianceLongitude INTEGER (0..9223372036854775807),
	varianceLatitude  INTEGER (0..9223372036854775807)
}
END
```
when compiled and built, fails to produce APER (or UPER) file from the following XER encoding (no pun intended :)):
```
<Test>
    <varianceLongitude>4</varianceLongitude>
    <varianceLatitude>223372036854775807</varianceLatitude>
</Test>
```

Here's what the debugging log says:
```
$ ./progname -dd -ixer -oaper Test.xer > Test.aper
AD: Processing Test.xer
AD: Decoding 120 bytes
AD: decode(0) consumed 119+0b (120), code 0
AD: => add_bytes(1) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1 (1 time)
AD: <= add_bytes(1) { o=0 l=1 u=0, s=1 }
AD: RC_OK, finishing up with 0+0
AD: Encoded in 0 bits of UPER
AD: Processing Test.xer
AD: Decoding 1 bytes
AD: decode(1) consumed 1+0b (1), code 1
AD: RC_WMORE, continuing read=0, cons=1  with 1..0-0..1
AD: Clean up partially decoded structure
$ ll Test.aper
-rw-r--r--  1 mouse  staff  0 Mar 21 23:13 Test.aper
$ 
```
I.e., resulting APER file is empty.

**Comment by velichkov** [comment]
Hi @mouse07410,

> AD: Encoded in 0 bits of UPER            <===== why UPER? why 0 bytes?

I fixed the encode in #4. The UPER instead of APER was just a copy pasted debug message. 

```
$ ./progname -dd -ixer -oaper Test.xer  > Test.aper
AD: Processing Test.xer
AD: Decoding 120 bytes
AD: decode(0) consumed 119+0b (120), code 0
AD: => add_bytes(1) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1 (1 time)
AD: <= add_bytes(1) { o=0 l=1 u=0, s=1 }
AD: RC_OK, finishing up with 0+0
AD: Encoded in 96 bits of APER
AD: Processing Test.xer
AD: Decoding 1 bytes
AD: decode(1) consumed 1+0b (1), code 1
AD: RC_WMORE, continuing read=0, cons=1  with 1..0-0..1
AD: Clean up partially decoded structure
```
```
 ./progname -dd -ixer -oper Test.xer  > Test.uper
AD: Processing Test.xer
AD: Decoding 120 bytes
AD: decode(0) consumed 119+0b (120), code 0
AD: => add_bytes(1) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1 (1 time)
AD: <= add_bytes(1) { o=0 l=1 u=0, s=1 }
AD: RC_OK, finishing up with 0+0
AD: Encoded in 126 bits of UPER
AD: Processing Test.xer
AD: Decoding 1 bytes
AD: decode(1) consumed 1+0b (1), code 1
AD: RC_WMORE, continuing read=0, cons=1  with 1..0-0..1
AD: Clean up partially decoded structure
```

**Comment by mouse07410** [comment]
Thank you! Compiles, and encodes APER.

But it seems to fail to decode it:
```
$ ./progname -ixer -otext Test.xer
Test ::= {
    varianceLongitude: 4
    varianceLatitude: 223372036854775807
}
$ ./progname -c -dd -ixer -oaper Test.xer > Test.aper
AD: Processing Test.xer
AD: Decoding 120 bytes
AD: decode(0) consumed 119+0b (120), code 0
AD: => add_bytes(1) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1 (1 time)
AD: <= add_bytes(1) { o=0 l=1 u=0, s=1 }
AD: RC_OK, finishing up with 0+0
AD: Encoded in 96 bits of APER
AD: Processing Test.xer
AD: Decoding 1 bytes
AD: decode(1) consumed 1+0b (1), code 1
AD: RC_WMORE, continuing read=0, cons=1  with 1..0-0..1
AD: Clean up partially decoded structure
$ ./progname -c -dd -iaper -otext Test.aper
AD: Processing Test.aper
AD: Decoding 12 bytes
AD: decode(0) consumed 0+0b (12), code 1
AD: => add_bytes(12) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 12 (1 time)
AD: <= add_bytes(12) { o=0 l=12 u=0, s=12 }
AD: RC_WMORE, continuing read=12, cons=0  with 0..12-0..12
AD: Decoding 12 bytes
AD: decode(12) consumed 0+0b (12), code 1
AD: RC_WMORE, continuing read=0, cons=0  with 0..12-0..12
AD: Clean up partially decoded structure
AD: ofp 1, no=0, oo=0, dbl=12
Test.aper: Decode failed past byte 0: Unexpected end of input
$ 
```

**Comment by mouse07410** [comment]
A bit more on this APER issue:
```
$ cat Test.xer
<Test>
    <varianceLongitude>9223372036854775807</varianceLongitude>
    <varianceLatitude>223372036854775807</varianceLatitude>
</Test>
$ ./progname -ixer -oaper Test.xer > Test.aper
$ ./progname -iaper -otext Test.aper
Test.aper: Decode failed past byte 0: Unexpected end of input
$ ./progname -c -dd -ixer -oaper Test.xer > Test.aper
AD: Processing Test.xer
AD: Decoding 138 bytes
AD: decode(0) consumed 137+0b (138), code 0
AD: => add_bytes(1) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1 (1 time)
AD: <= add_bytes(1) { o=0 l=1 u=0, s=1 }
AD: RC_OK, finishing up with 0+0
AD: Encoded in 160 bits of APER
AD: Processing Test.xer
AD: Decoding 1 bytes
AD: decode(1) consumed 1+0b (1), code 1
AD: RC_WMORE, continuing read=0, cons=1  with 1..0-0..1
AD: Clean up partially decoded structure
$ ./progname -c -dd -iaper -otext Test.aper
AD: Processing Test.aper
AD: Decoding 20 bytes
AD: decode(0) consumed 0+0b (20), code 1
AD: => add_bytes(20) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 20 (1 time)
AD: <= add_bytes(20) { o=0 l=20 u=0, s=20 }
AD: RC_WMORE, continuing read=20, cons=0  with 0..20-0..20
AD: Decoding 20 bytes
AD: decode(20) consumed 0+0b (20), code 1
AD: RC_WMORE, continuing read=0, cons=0  with 0..20-0..20
AD: Clean up partially decoded structure
AD: ofp 1, no=0, oo=0, dbl=20
Test.aper: Decode failed past byte 0: Unexpected end of input
$ od -t x1 Test.aper
0000000    80  ff  7f  ff  ff  ff  ff  ff  ff  ff  80  ff  03  19  93  af
0000020    1d  7b  ff  ff                                                
0000024
$
```

**Pull request merged**
