### PR TITLE
Fix NativeInteger DER/UPER/APER encode

### PR DESCRIPTION
**Pull request by velichkov**
Fixes from mouse07410#4 for 115 branch

### CODE REVIEW

**Comment by mouse07410** [comment]
First, **thank you**!

Second, I wonder if your 02dc396 covers *only* UPER? Because it would be nice if larger constraints worked for both UPER and APER.

Finally, a few months ago somebody reported a problem with the following ASN.1:
```
Test2b DEFINITIONS ::=
BEGIN

Test2b ::= SEQUENCE {

      count INTEGER (0..20000),
      data  OCTET STRING SIZE (40..20000)
}
```

I've tried it, but got hit-and-miss. Some files seem to encode and decode OK, and some fail. Here's one example of the failing file (`test2b_1789_octet.xer`):
```
<Test2b>
    <count>1789</count>
    <data>
        6B 62 2D 04 60 C2 8D 5F F5 BF 21 44 61 C1 82 F3 
        51 BA 95 DE 12 17 FC 5F E0 5C BB 42 DC 95 D1 CD 
        8E 2E 30 AE 61 5D 1B 4A F9 35 AB 87 E9 18 45 0C 
        48 92 D3 4D 29 EA 69 C8 05 53 82 57 C1 EC 8F 07 
        CD EC 67 6B 1B CE 41 60 B6 83 03 DD 01 DB 28 80 
        23 A7 B2 AD 51 91 F8 80 A9 95 AD 4F C6 65 17 EB 
        15 6B 05 8F 1A 0C 66 BB 58 FE 39 5C 38 4A 0A 40 
        83 8C 56 F0 F5 8E F2 EB 6A 86 F8 BD D6 86 78 14 
        5D 2F 98 2F E9 E6 FE 82 7A DD 6D 94 53 AE 95 EF 
        00 BC A3 29 5C 8B AC ED 3B F3 47 EB 10 D5 C4 F3 
        A9 41 A5 8E 58 FD 7F 4C B5 42 CF 58 F9 01 0B 9D 
        21 3A B1 1E 8A 32 8B 5B AC AF 3F A5 C1 07 1F 6C 
        91 8E F8 FE 63 8C 27 42 8C AF 07 48 83 BB 21 84 
        F5 45 F4 8D 1A 3C 9D 8F 73 AF 45 1F FC BF C6 91 
        6A E5 0D 3B E2 E4 09 DC 6F F5 C8 C6 1E DA BE B2 
        13 8F 97 8B FD A2 32 E6 2A 13 DC 65 E5 BE AF 74 
        5B FD BC D6 58 05 EC C5 CF 66 CE B2 3F 1B 50 FE 
        5C CA E9 99 44 FB BE 7F BD B3 31 FC B8 10 39 24 
        87 E0 8D BE F2 5D DB 38 9B C2 92 C2 E8 15 2E 84 
        C9 30 F6 10 FB B4 DE 86 7E 6A 63 BA DB 4B 98 D0 
        23 E6 29 50 E7 38 83 BD 29 CC 87 07 AC 66 BD 02 
        DC E2 5F 7D D8 84 E5 BF 6A BB 5A 09 15 ED 06 88 
        BF 8B 16 E0 02 54 82 60 33 D4 01 C9 1B 41 49 4E 
        97 D3 E2 FE 78 C4 DB A8 48 93 30 CE 80 D5 A0 3B 
        7B 1A DA 36 B0 82 BA 7D 27 25 70 86 62 4A DE 3A 
        D0 D8 5E 62 86 74 C9 67 82 4C 4C 0A 89 17 61 2B 
        13 F5 A0 2B A8 E0 D8 98 C9 66 AF 41 8A 84 8D FF 
        AB 60 1F 07 9E 51 2C C7 A6 2E A9 BC 9B C2 D6 8B 
        46 0B 0D 8F 00 DC A3 ED 7E 12 46 7B 1C 84 33 69 
        FF 04 4D E1 BE 92 86 10 AD 2C F8 3E BB 5A 97 89 
        6E 33 34 2B EF 0D 36 BB 22 77 0B 4B 75 F6 B4 A7 
        B9 78 61 FC 3E 80 42 16 1B 79 87 30 D3 49 D6 9A 
        F1 9C 08 F5 7C B1 BF 6F E4 27 6B 52 20 AA 41 2C 
        73 98 E3 06 2D B4 04 AB 20 A0 0F 77 47 94 1F BC 
        5C E4 B1 FB 66 0B AD A3 FB A4 4D 13 8E 6B 74 73 
        89 73 14 A7 E5 56 34 05 DC DF 0D 5C A8 0F 8A D0 
        C7 61 2C 84 BE 13 79 7E FC 29 A9 A1 99 97 1F ED 
        68 DF E8 0A 36 45 AD A7 F6 0B A7 AF 9D 2B 44 0D 
        2F D5 59 49 11 A5 C1 A4 7B 1F 2C 31 6C 26 99 00 
        94 4F 89 43 BB C1 82 5F FC 59 5A AD 13 8A 08 30 
        92 23 7D FE C4 6E 33 D9 76 3B D5 B7 A4 7B 67 EE 
        F4 F9 83 95 8E 3D 49 7D 6B 11 02 CD E5 ED 8D CC 
        28 4A 4C 26 BD 38 E4 1E 26 96 FC 36 82 5D BB 4E 
        AD A5 7F 1A DC 0E D9 40 C1 7C 1A C5 B4 68 6B 50 
        5E FE AC 48 73 14 8D 17 90 C6 6D 78 A6 9B 45 04 
        D1 C8 5A C8 AB 64 AA 69 E6 6A 67 18 C5 03 09 7F 
        4A 27 7B 11 84 29 89 E5 CF 22 3F C5 CD 7C 6A 65 
        63 88 37 F7 8C FD 1A 21 B1 C3 3D 10 53 DA A4 A7 
        3E 7D 39 AC 56 24 C1 1A AE EA D8 EA 4B 7B DD 41 
        4B 3C 33 B7 42 34 68 DB 38 58 C1 BE B3 1D 2F 77 
        DD D0 7A 86 CB CD D4 13 51 52 98 01 35 C9 4B 72 
        BF 79 F4 A3 1C 45 7C A9 07 68 2B 94 74 E0 14 0F 
        43 F2 F0 FF 41 99 0D 22 6B E5 4F 80 BF 6B 9F 4A 
        C5 A0 15 3D 2B 4E 36 C4 A0 D2 D8 76 79 76 C5 4E 
        39 D4 69 98 E1 DE B8 E7 D6 C1 9A 51 B7 87 D1 07 
        5C 98 23 53 4C 49 EA 2A 6C F1 3D DC F7 A3 D3 E2 
        84 05 2E 93 0B DF 75 6F F0 3A 50 9A 3D 19 42 16 
        D0 0C B4 2C 0F D9 A6 2B 5E 81 D7 E6 0C 02 53 60 
        91 0E DF 27 DC 01 AE 48 4D 1D F5 E4 7D 86 BE 78 
        0D 4C 57 8D C3 2D E8 DB 95 A5 C9 76 CF 70 3F 3C 
        DB DF 94 1A 37 F8 5E BB E8 E8 72 6F F2 62 1A EE 
        88 86 AD 9F 7D 90 72 19 E3 4F C6 14 4B DE B8 F8 
        6C A0 09 4F 40 29 3F C7 35 F4 89 6E 94 66 53 94 
        E7 8F F8 1D C5 68 76 86 72 6C 82 49 58 49 33 70 
        3F 98 5D BA D6 04 1A 7A 18 1C 8A A4 E6 2B 08 28 
        43 DA 2E 96 88 16 D3 F0 20 01 6A CB C2 F0 BD A6 
        B0 70 09 29 72 8D B6 48 0A 53 C6 77 77 5F 67 84 
        D2 16 E5 6B DC A6 18 F3 59 59 50 9E D3 9C B5 ED 
        D9 7E F2 B2 BC DB 12 5A 00 26 61 B7 DA 13 4E C2 
        82 99 68 16 22 77 7C E8 11 8D 95 90 FA 2F 79 46 
        1C 30 6A 4C FB 92 B8 E6 AF F4 E2 76 36 88 A7 96 
        1B B6 F3 2D 74 E5 A7 E9 2B 5F 44 76 6C 14 C4 DB 
        1F 5E D0 70 55 DB 9B CE 65 AC D1 65 39 01 15 DB 
        99 BD FD C2 5F 58 93 44 13 C6 E9 3B B7 29 E1 CA 
        89 F6 2B 82 9E 3E 4C 04 75 EA A8 50 4B BF 06 B2 
        C7 27 ED 2B 74 90 4B 00 38 0B 81 33 E4 0A D8 5D 
        37 59 5F 93 F6 D8 33 6E 7C A5 53 69 17 96 D1 01 
        58 42 B0 18 11 C0 BD 2B 5F 13 7C C2 AF D2 4A 84 
        AC 99 29 84 E8 60 29 CD F5 63 FF DA BD 24 81 94 
        73 59 91 FC 10 F5 0F FA 36 D9 20 3B AA F3 C1 99 
        FD 23 40 B7 30 4D E8 12 8A 1D F2 BC 90 D6 87 D7 
        7B 61 5F A5 15 ED 54 D5 5E FC 39 DB 4A 23 D3 A2 
        15 76 D5 FB 21 FA 9F 19 02 D4 CE 4E FD 77 42 30 
        D2 63 BD F8 C8 61 0E E0 95 F1 6E 16 4C 77 DB 70 
        2E 60 13 86 FD 66 A3 D1 CC 3A 89 90 AF 66 40 C2 
        B9 E4 ED C2 50 DD D5 DE 41 F4 A4 94 CE 94 A7 C0 
        EF F5 DC E5 A9 F8 3A 2D 24 48 0C 79 9E 81 73 71 
        F3 06 08 73 6A F4 04 B4 F4 03 2E FF 2B AB 49 57 
        2D 27 5A 57 C6 94 20 75 5A FC ED 44 05 1E 1C 8A 
        D1 55 68 92 08 74 18 47 1F 4A 24 E9 EE F4 8E 86 
        7D 29 07 8C 16 31 7E C5 04 C0 84 2B 74 AF 25 12 
        F4 4F 7D BD 32 15 AB 8D EA 27 5C CC C4 24 B0 53 
        67 85 74 64 44 06 4F 65 C5 E1 D5 7C FB D3 AD B6 
        27 A6 2D 16 35 3C 57 04 86 8E 29 A6 21 A5 B3 AA 
        A0 E7 E9 01 A3 F3 59 3D 71 F9 63 D5 FB B0 16 5C 
        93 42 14 7A 85 25 19 DF 56 5C FA 53 26 CB 25 37 
        72 EF F9 CE 86 82 90 B6 5E 92 BE 8A 37 81 34 05 
        B5 0E 5B 1E 7A BC BB 46 CB 87 80 77 EA D4 61 00 
        DC 8C AE 00 E6 10 B1 57 D0 25 EF F9 AB B9 00 F7 
        F7 E1 0A C9 D6 BE CE 62 67 48 9F F8 0B 64 48 8D 
        5D 94 09 5D 83 90 C8 51 AC 6D FC 3D 25 6F E6 25 
        17 90 4A 7B 8A E2 92 85 2C 62 41 4E 16 EA 7A EB 
        D9 12 25 92 AC F0 16 A6 F4 6C D9 69 C1 5C 56 F8 
        30 D2 69 72 FC 6B BB AE C2 9D 08 1A 7E 0F CC A8 
        FB B4 E6 50 A3 1D 30 21 E9 EA A1 37 9B EE 25 0A 
        53 1E 7E DB 14 FE 02 AD AD CD 7C 64 C2 0E 4C 98 
        F5 15 A8 D7 1B 5C 64 73 FC D8 F0 A3 35 BB D3 1B 
        84 D2 F1 3E 52 DB 9E B6 B7 A5 8D AF 2C 11 0E EF 
        AE 45 DB 9A E9 1D 90 24 B4 DA D9 72 E8 DA FE CD 
        27 55 C3 52 6F 25 52 BA 31 F9 29 69 85 8A 6E A3 
        55 92 F4 81 BD ED 85 D5 6F 80 32 41 48 EF 80 1C 
        F5 26 66 99 72 67 F8 28 A8 43 27 B0 30
    </data>
</Test2b>
```

Conversion to/from UPER works fine.

Conversion to APER seems to work, but decoding the resulting APER fails:
```
$ ./test2b -ixer -oaper test2b_1789_octet.xer > test2b_1789_octet.aper
$ ./test2b -c -dd -iaper test2b_1789_octet.aper
AD: Processing test2b_1789_octet.aper
AD: Decoding 1793 bytes
AD: decode(0) consumed 0+0b (1793), code 1
AD: => add_bytes(1793) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 1793 (1 time)
AD: <= add_bytes(1793) { o=0 l=1793 u=0, s=1793 }
AD: RC_WMORE, continuing read=1793, cons=0  with 0..1793-0..1793
AD: Decoding 1793 bytes
AD: decode(1793) consumed 0+0b (1793), code 1
AD: RC_WMORE, continuing read=0, cons=0  with 0..1793-0..1793
AD: Clean up partially decoded structure
AD: ofp 1, no=0, oo=0, dbl=1793
test2b_1789_octet.aper: Decode failed past byte 0: Unexpected end of input
$
```

Perhaps you know what seems to be wrong, and how to address it?

**Comment by velichkov** [comment]
> First, thank you!

No problem

> Second, I wonder if your 02dc396 covers only UPER? Because it would be nice if larger constraints worked for both UPER and APER.

Yes, it is UPER only. Right now there is no any APER tests so I'm going to modify check-127.-gen-PER.c
check-132.-gen-PER.c, check-133.-gen-PER.c, check64-134.-gen-PER.c tests to check both UPER and APER encode/decode

>Finally, a few months ago somebody reported a problem with the following ASN.1:
>I've tried it, but got hit-and-miss. Some files seem to encode and decode OK, and some fail. Here's one example of the failing file (test2b_1789_octet.xer):

and I'm going to add a separate test case for this

**Comment by mouse07410** [comment]
> I'm going to modify check-127.-gen-PER.c
check-132.-gen-PER.c, check-133.-gen-PER.c, check64-134.-gen-PER.c tests to check both UPER and APER encode/decode

**Great**!  Thank you!!

**Comment by mouse07410** [comment]
Now I find an interesting situation. APER produced by the current master, fails to be parsed by 115 at all.

APER produced by the current (with merged #8) 115, is parsed by the master - but with an error in the end:
```
<Test2b>
    <count>1789</count>
    <data>
        6B 62 2D 04 60 C2 8D 5F F5 BF 21 44 61 C1 82 F3 
        51 BA 95 DE 12 17 FC 5F E0 5C BB 42 DC 95 D1 CD 
        8E 2E 30 AE 61 5D 1B 4A F9 35 AB 87 E9 18 45 0C 
        48 92 D3 4D 29 EA 69 C8 05 53 82 57 C1 EC 8F 07 
        CD EC 67 6B 1B CE 41 60 B6 83 03 DD 01 DB 28 80 
        23 A7 B2 AD 51 91 F8 80 A9 95 AD 4F C6 65 17 EB 
        15 6B 05 8F 1A 0C 66 BB 58 FE 39 5C 38 4A 0A 40 
        83 8C 56 F0 F5 8E F2 EB 6A 86 F8 BD D6 86 78 14 
        5D 2F 98 2F E9 E6 FE 82 7A DD 6D 94 53 AE 95 EF 
        00 BC A3 29 5C 8B AC ED 3B F3 47 EB 10 D5 C4 F3 
        A9 41 A5 8E 58 FD 7F 4C B5 42 CF 58 F9 01 0B 9D 
        21 3A B1 1E 8A 32 8B 5B AC AF 3F A5 C1 07 1F 6C 
        91 8E F8 FE 63 8C 27 42 8C AF 07 48 83 BB 21 84 
        F5 45 F4 8D 1A 3C 9D 8F 73 AF 45 1F FC BF C6 91 
        6A E5 0D 3B E2 E4 09 DC 6F F5 C8 C6 1E DA BE B2 
        13 8F 97 8B FD A2 32 E6 2A 13 DC 65 E5 BE AF 74 
        5B FD BC D6 58 05 EC C5 CF 66 CE B2 3F 1B 50 FE 
        5C CA E9 99 44 FB BE 7F BD B3 31 FC B8 10 39 24 
        87 E0 8D BE F2 5D DB 38 9B C2 92 C2 E8 15 2E 84 
        C9 30 F6 10 FB B4 DE 86 7E 6A 63 BA DB 4B 98 D0 
        23 E6 29 50 E7 38 83 BD 29 CC 87 07 AC 66 BD 02 
        DC E2 5F 7D D8 84 E5 BF 6A BB 5A 09 15 ED 06 88 
        BF 8B 16 E0 02 54 82 60 33 D4 01 C9 1B 41 49 4E 
        97 D3 E2 FE 78 C4 DB A8 48 93 30 CE 80 D5 A0 3B 
        7B 1A DA 36 B0 82 BA 7D 27 25 70 86 62 4A DE 3A 
        D0 D8 5E 62 86 74 C9 67 82 4C 4C 0A 89 17 61 2B 
        13 F5 A0 2B A8 E0 D8 98 C9 66 AF 41 8A 84 8D FF 
        AB 60 1F 07 9E 51 2C C7 A6 2E A9 BC 9B C2 D6 8B 
        46 0B 0D 8F 00 DC A3 ED 7E 12 46 7B 1C 84 33 69 
        FF 04 4D E1 BE 92 86 10 AD 2C F8 3E BB 5A 97 89 
        6E 33 34 2B EF 0D 36 BB 22 77 0B 4B 75 F6 B4 A7 
        B9 78 61 FC 3E 80 42 16 1B 79 87 30 D3 49 D6 9A 
        F1 9C 08 F5 7C B1 BF 6F E4 27 6B 52 20 AA 41 2C 
        73 98 E3 06 2D B4 04 AB 20 A0 0F 77 47 94 1F BC 
        5C E4 B1 FB 66 0B AD A3 FB A4 4D 13 8E 6B 74 73 
        89 73 14 A7 E5 56 34 05 DC DF 0D 5C A8 0F 8A D0 
        C7 61 2C 84 BE 13 79 7E FC 29 A9 A1 99 97 1F ED 
        68 DF E8 0A 36 45 AD A7 F6 0B A7 AF 9D 2B 44 0D 
        2F D5 59 49 11 A5 C1 A4 7B 1F 2C 31 6C 26 99 00 
        94 4F 89 43 BB C1 82 5F FC 59 5A AD 13 8A 08 30 
        92 23 7D FE C4 6E 33 D9 76 3B D5 B7 A4 7B 67 EE 
        F4 F9 83 95 8E 3D 49 7D 6B 11 02 CD E5 ED 8D CC 
        28 4A 4C 26 BD 38 E4 1E 26 96 FC 36 82 5D BB 4E 
        AD A5 7F 1A DC 0E D9 40 C1 7C 1A C5 B4 68 6B 50 
        5E FE AC 48 73 14 8D 17 90 C6 6D 78 A6 9B 45 04 
        D1 C8 5A C8 AB 64 AA 69 E6 6A 67 18 C5 03 09 7F 
        4A 27 7B 11 84 29 89 E5 CF 22 3F C5 CD 7C 6A 65 
        63 88 37 F7 8C FD 1A 21 B1 C3 3D 10 53 DA A4 A7 
        3E 7D 39 AC 56 24 C1 1A AE EA D8 EA 4B 7B DD 41 
        4B 3C 33 B7 42 34 68 DB 38 58 C1 BE B3 1D 2F 77 
        DD D0 7A 86 CB CD D4 13 51 52 98 01 35 C9 4B 72 
        BF 79 F4 A3 1C 45 7C A9 07 68 2B 94 74 E0 14 0F 
        43 F2 F0 FF 41 99 0D 22 6B E5 4F 80 BF 6B 9F 4A 
        C5 A0 15 3D 2B 4E 36 C4 A0 D2 D8 76 79 76 C5 4E 
        39 D4 69 98 E1 DE B8 E7 D6 C1 9A 51 B7 87 D1 07 
        5C 98 23 53 4C 49 EA 2A 6C F1 3D DC F7 A3 D3 E2 
        84 05 2E 93 0B DF 75 6F F0 3A 50 9A 3D 19 42 16 
        D0 0C
    </data>
</Test2b>
test2b_1789_octet.aper: Decode failed past byte 918: Unexpected end of input
```

Any comments/opinion?

**Comment by velichkov** [comment]
> Now I find an interesting situation. APER produced by the current master, fails to be parsed by 115 at all (all the APER files I tried, not just this one).

That is expected as similar fixes have to be implemented in master as well. 
First the [`OCTET_STRING_encode_aper`](https://github.com/mouse07410/asn1c/blob/master/skeletons/OCTET_STRING.c#L1959-L1960) should calls `aper_put_length` instead of `per_put_few_bits`. And the [`per_put_length`](https://github.com/mouse07410/asn1c/blob/master/skeletons/per_support.c#L727-L733) have to be fixed as now it is pretty much copy-paste of `uper_put_length`, it should take the range as parameter (similar to the 115 branch) and based on the range it should determine in how much bytes the given length must be encoded.

Unfortunately in the next few weeks I won't have much time to work on this.

> APER produced by the current (with merged #8) 115, is parsed by the master - but with an error in the end:test2b_1789_octet.aper: Decode failed past byte 918: Unexpected end of input
> 
> Any comments/opinion?

I can't reproduce this problem, could you send me the test2b_1789_octet.aper that you are testing with?
Here si mine [test2b_1789_octet.aper.tar.gz](https://github.com/mouse07410/asn1c/files/882969/test2b_1789_octet.aper.tar.gz), could you try to decode it?

**Comment by mouse07410** [comment]
> Unfortunately in the next few weeks I won't have much time to work on this.

You've already helped very much!

> Here is mine [test2b_1789_octet.aper.tar.gz](https://github.com/mouse07410/asn1c/files/882969/test2b_1789_octet.aper.tar.gz), could you try to decode it?

Sure - here's the output (decoding your test-file with the current master):
```
$ ll test2b_1789_octet.aper
-rw-r--r--@ 1 mouse ...  1793 Mar 30 11:41 test2b_1789_octet.aper
$ ./test2b -c -dd -iaper ~/src/asn1c/test2b_1789_octet.aper 
AD: Processing /Users/ur20980/src/asn1c/test2b_1789_octet.aper
AD: Decoding 1793 bytes
AD: decode(0) consumed 918+0b (1793), code 0
AD: => add_bytes(875) { o=0 l=0 u=0, s=0 }
AD: 	Buffer reallocated to 875 (1 time)
AD: <= add_bytes(875) { o=0 l=875 u=0, s=875 }
AD: RC_OK, finishing up with 0+0
<Test2b>
    <count>1829</count>
    <data>
        6B 62 2D 04 60 C2 8D 5F F5 BF 21 44 61 C1 82 F3 
        51 BA 95 DE 12 17 FC 5F E0 5C BB 42 DC 95 D1 CD 
        8E 2E 30 AE 61 5D 1B 4A F9 35 AB 87 E9 18 45 0C 
        48 92 D3 4D 29 EA 69 C8 05 53 82 57 C1 EC 8F 07 
        CD EC 67 6B 1B CE 41 60 B6 83 03 DD 01 DB 28 80 
        23 A7 B2 AD 51 91 F8 80 A9 95 AD 4F C6 65 17 EB 
        15 6B 05 8F 1A 0C 66 BB 58 FE 39 5C 38 4A 0A 40 
        83 8C 56 F0 F5 8E F2 EB 6A 86 F8 BD D6 86 78 14 
        5D 2F 98 2F E9 E6 FE 82 7A DD 6D 94 53 AE 95 EF 
        00 BC A3 29 5C 8B AC ED 3B F3 47 EB 10 D5 C4 F3 
        A9 41 A5 8E 58 FD 7F 4C B5 42 CF 58 F9 01 0B 9D 
        21 3A B1 1E 8A 32 8B 5B AC AF 3F A5 C1 07 1F 6C 
        91 8E F8 FE 63 8C 27 42 8C AF 07 48 83 BB 21 84 
        F5 45 F4 8D 1A 3C 9D 8F 73 AF 45 1F FC BF C6 91 
        6A E5 0D 3B E2 E4 09 DC 6F F5 C8 C6 1E DA BE B2 
        13 8F 97 8B FD A2 32 E6 2A 13 DC 65 E5 BE AF 74 
        5B FD BC D6 58 05 EC C5 CF 66 CE B2 3F 1B 50 FE 
        5C CA E9 99 44 FB BE 7F BD B3 31 FC B8 10 39 24 
        87 E0 8D BE F2 5D DB 38 9B C2 92 C2 E8 15 2E 84 
        C9 30 F6 10 FB B4 DE 86 7E 6A 63 BA DB 4B 98 D0 
        23 E6 29 50 E7 38 83 BD 29 CC 87 07 AC 66 BD 02 
        DC E2 5F 7D D8 84 E5 BF 6A BB 5A 09 15 ED 06 88 
        BF 8B 16 E0 02 54 82 60 33 D4 01 C9 1B 41 49 4E 
        97 D3 E2 FE 78 C4 DB A8 48 93 30 CE 80 D5 A0 3B 
        7B 1A DA 36 B0 82 BA 7D 27 25 70 86 62 4A DE 3A 
        D0 D8 5E 62 86 74 C9 67 82 4C 4C 0A 89 17 61 2B 
        13 F5 A0 2B A8 E0 D8 98 C9 66 AF 41 8A 84 8D FF 
        AB 60 1F 07 9E 51 2C C7 A6 2E A9 BC 9B C2 D6 8B 
        46 0B 0D 8F 00 DC A3 ED 7E 12 46 7B 1C 84 33 69 
        FF 04 4D E1 BE 92 86 10 AD 2C F8 3E BB 5A 97 89 
        6E 33 34 2B EF 0D 36 BB 22 77 0B 4B 75 F6 B4 A7 
        B9 78 61 FC 3E 80 42 16 1B 79 87 30 D3 49 D6 9A 
        F1 9C 08 F5 7C B1 BF 6F E4 27 6B 52 20 AA 41 2C 
        73 98 E3 06 2D B4 04 AB 20 A0 0F 77 47 94 1F BC 
        5C E4 B1 FB 66 0B AD A3 FB A4 4D 13 8E 6B 74 73 
        89 73 14 A7 E5 56 34 05 DC DF 0D 5C A8 0F 8A D0 
        C7 61 2C 84 BE 13 79 7E FC 29 A9 A1 99 97 1F ED 
        68 DF E8 0A 36 45 AD A7 F6 0B A7 AF 9D 2B 44 0D 
        2F D5 59 49 11 A5 C1 A4 7B 1F 2C 31 6C 26 99 00 
        94 4F 89 43 BB C1 82 5F FC 59 5A AD 13 8A 08 30 
        92 23 7D FE C4 6E 33 D9 76 3B D5 B7 A4 7B 67 EE 
        F4 F9 83 95 8E 3D 49 7D 6B 11 02 CD E5 ED 8D CC 
        28 4A 4C 26 BD 38 E4 1E 26 96 FC 36 82 5D BB 4E 
        AD A5 7F 1A DC 0E D9 40 C1 7C 1A C5 B4 68 6B 50 
        5E FE AC 48 73 14 8D 17 90 C6 6D 78 A6 9B 45 04 
        D1 C8 5A C8 AB 64 AA 69 E6 6A 67 18 C5 03 09 7F 
        4A 27 7B 11 84 29 89 E5 CF 22 3F C5 CD 7C 6A 65 
        63 88 37 F7 8C FD 1A 21 B1 C3 3D 10 53 DA A4 A7 
        3E 7D 39 AC 56 24 C1 1A AE EA D8 EA 4B 7B DD 41 
        4B 3C 33 B7 42 34 68 DB 38 58 C1 BE B3 1D 2F 77 
        DD D0 7A 86 CB CD D4 13 51 52 98 01 35 C9 4B 72 
        BF 79 F4 A3 1C 45 7C A9 07 68 2B 94 74 E0 14 0F 
        43 F2 F0 FF 41 99 0D 22 6B E5 4F 80 BF 6B 9F 4A 
        C5 A0 15 3D 2B 4E 36 C4 A0 D2 D8 76 79 76 C5 4E 
        39 D4 69 98 E1 DE B8 E7 D6 C1 9A 51 B7 87 D1 07 
        5C 98 23 53 4C 49 EA 2A 6C F1 3D DC F7 A3 D3 E2 
        84 05 2E 93 0B DF 75 6F F0 3A 50 9A 3D 19 42 16 
        D0 0C
    </data>
</Test2b>
AD: Processing /Users/ur20980/src/asn1c/test2b_1789_octet.aper
AD: Decoding 875 bytes
AD: decode(875) consumed 0+0b (875), code 1
AD: RC_WMORE, continuing read=0, cons=0  with 0..875-0..875
AD: Clean up partially decoded structure
AD: ofp 0, no=918, oo=918, dbl=875
/Users/ur20980/src/asn1c/test2b_1789_octet.aper: Decode failed past byte 918: Unexpected end of input
$
```

**Comment by mouse07410** [comment]
@velichkov , whatever encoding I do with 115, the numbers turn out right. So I assume this issue has been dealt with adequately.

My main remaining concern with this release is https://github.com/vlm/asn1c/issues/137. I'd say if we can fix it (aka make sure calling `[ua]per_encode(&structure, ptr_to_buf, 0, 0)` returns the required size of the buffer to hold the encoded PDU, we can call the release v1.0.0. Reason: in addition to multiple bug fixes, this code now supports APER, supports wider PER constraints, includes EXTERNAL and Info Object support... What's your take on this?

**Comment by velichkov** [comment]
Hi,

I was able to reproduce the `Decode failed past byte 918: Unexpected end of input` problem with the old master but I don't have much time to debug the aper code that comes from vlm/asn1c#125. My guess is that the problem is somewhere in `aper_get_length`

> One observation - the reported length (and the value of the count field) does not match the file name. It appears that the content was generated with count=1829, while the file was named ...1789.... Also, it appears to read 1793 bytes (1789 bytes of the OCTET STRING, and some bytes for the INTEGER).
>
> Did you just set the count value to 1829? 

No, I used 1789.

>Or is it a problem with 115?

My guess is that this is a problem with 125 and not 115. 

> whatever encoding I do with 115, the numbers turn out right. So I assume this issue has been dealt with adequately. Update: although if/when you could validate this, I'd love to hear your confirmation.

I think it is good enough.

> My main remaining concern with this release is vlm#137. I'd say if we can fix it (aka make sure calling [ua]per_encode(&structure, ptr_to_buf, 0, 0) returns the required size of the buffer to hold the encoded PDU, 

Done in mouse07410/asn1c#9

> we can call the release v1.0.0. Reason: in addition to multiple bug fixes, this code now supports APER, supports wider PER constraints, includes EXTERNAL and Info Object support... What's your take on this?

Yes, it will be great to have a new major release with all these features and although mouse07410/asn1c#7 breaks the API and require changes in the application I think it will be good to include it too.

**Comment by mouse07410** [comment]
> Yes, it will be great to have a new major release with all these features and although mouse07410/asn1c#7 breaks the API and require changes in the application I think it will be good to include it too.

OK, let me contemplate on it for a bit - and I'll probably merge it in the next few days.

**Pull request merged**
