### PR TITLE
rename HAVE_CONFIG_H to HAVE_ASN1C_CONFIG_H

### LINKED ISSUE #201: Can we rename HAVE_CONFIG_H?
`HAVE_CONFIG_H` is also defined by [CppUTest](https://github.com/cpputest/cpputest), and trying to use it with asn1c generated code is causing slight annoyance

Can we rename `HAVE_CONFIG_H` to `ASN1C_HAVE_CONFIG_H`?

I'm not super sure what `HAVE_CONFIG_H` is supposed to be for, it's not mentioned in any documentation

### PR DESCRIPTION
**Pull request by mtfurlan**
other projects like CppUTest also use HAVE_CONFIG_H so this will reduce
conflicts

Closes #201

### CODE REVIEW

**Comment by mtfurlan** [comment]
Hm, I didn't expect this to fail to build, but clearly I did it wrong

**Comment by mtfurlan** [comment]
Okay so `HAVE_CONFIG_H` is generated by autotools with [`configure.ac`:`AC_CONFIG_HEADER([config.h])`](https://github.com/mouse07410/asn1c/blob/vlm_master/configure.ac#L4)

So to do this we would have to rename `config.h` to `config_asn1c.h`
Is this still acceptable?

**Comment by mtfurlan** [comment]
Okay I think HAVE_CONFIG_H is hardcoded by [autoreconf](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Configuration-Headers.html) and cannot be changed?

**Comment by mouse07410** [comment]
Now, wait a bit. Why are we interfering with the asn1c compiler build? It's not supposed to get linked with any other package out library, so whatever `config.h` other oxidates might have, should play no role here.

What are you trying to accomplish?

**Comment by kentkost** [comment]
I agree. It seems like more code is being added in order to fix something that is a "slight annoyance".
cpputest is not even used in asn1c.

What are you trying to accomplish?

**Comment by mtfurlan** [comment]
I'm generating asn1c, adding the files to a cmake target, and then linking that target against my code, my tests, and cpputest, and somehow HAVE_CONFIG_H is getting set by them

It seemed silly that two projects were using the same name for something, but now that I've read autoconf I'm pretty sure the name is set by them, so we cannot change it

**Pull request closed without merging**
