### PR TITLE
Merge PR143 to mouse07410's 115 branch

### PR DESCRIPTION
**Pull request by brchiu**
Merge [#143](https://github.com/vlm/asn1c/pull/143) to mouse07410's [115](https://github.com/mouse07410/asn1c/tree/115) branch.

### CODE REVIEW

**Comment by mouse07410** [comment]
I must confess I am now having second thoughts about merging this PR. Frankly, I did not realize that the UI gets changed. I somehow got the impression that only the internals changed.

This PR broke the User Interface (which is a big deal), and made the programs that used to compile and run - now fail to compile:
```
clang -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -DPDU=Test2b -I. -o m1b.o -c m1b.c
m1b.c:214:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, per_dec, 0); /* UPER-decoded */
        ~~~~~~~~~~~~~~ ^
m1b.c:267:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, per_dec, 0); /* UPER-decoded */
        ~~~~~~~~~~~~~~ ^
m1b.c:311:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, per_dec, 0);
        ~~~~~~~~~~~~~~ ^
m1b.c:334:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, t_p, 0);     /* Test2b PDU */
        ~~~~~~~~~~~~~~ ^
m1b.c:338:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, der_dec, 0); /* BER-decoded */
        ~~~~~~~~~~~~~~ ^
m1b.c:342:24: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_Test2b.free_struct(&asn_DEF_Test2b, per_dec, 0); /* PER-decoded */
        ~~~~~~~~~~~~~~ ^
6 errors generated.
make: *** [m1b.o] Error 1
```
This is one that I stumbled upon by accident. What other are there?

Can you please list all the introduced incompatibilities of this kind, and how user program should address them?

**Comment by mouse07410** [comment]
@brchiu I've merged against 115, but it fails against the new master:
```
  CC       check-PER-OCTET_STRING.o
check-PER-OCTET_STRING.c:45:52: warning: format specifies type 'int' but the argument has type 'size_t'
      (aka 'unsigned long') [-Wformat]
                        filename, lineno, lbound, ubound, rbits, ebits, dec_len, enc_len);
                                                                        ^~~~~~~
check-PER-OCTET_STRING.c:45:61: warning: format specifies type 'int' but the argument has type 'size_t'
      (aka 'unsigned long') [-Wformat]
                        filename, lineno, lbound, ubound, rbits, ebits, dec_len, enc_len);
                                                                                 ^~~~~~~
check-PER-OCTET_STRING.c:67:23: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_OCTET_STRING.free_struct(&asn_DEF_OCTET_STRING, &st, 1);
        ~~~~~~~~~~~~~~~~~~~~ ^
check-PER-OCTET_STRING.c:74:23: error: no member named 'free_struct' in 'struct asn_TYPE_descriptor_s'
        asn_DEF_OCTET_STRING.free_struct(&asn_DEF_OCTET_STRING, reconstructed_st, 0);
        ~~~~~~~~~~~~~~~~~~~~ ^
```
(which was fairly straightforward to fix by replacing `.free_struct()` with the appropriate macro `ASN_STRUCT_FREE...()`

and the checks (which I don't quite know how to fix):
```
Checking ../tests/136-OCTET-STRING-OK.asn1 against ../tests/136-OCTET-STRING-OK.asn1.-Pgen-PER
--- .tmp.check-parsing.26031.old	2017-04-07 16:17:11.000000000 -0400
+++ .tmp.check-parsing.26031.new	2017-04-07 16:17:11.000000000 -0400
@@ -127,18 +127,8 @@
 asn_TYPE_descriptor_t asn_DEF_PDU = {
 	"PDU",
 	"PDU",
-	SEQUENCE_free,
-	SEQUENCE_print,
+	&asn_OP_SEQUENCE,
 	SEQUENCE_constraint,
-	SEQUENCE_decode_ber,
-	SEQUENCE_encode_der,
-	SEQUENCE_decode_xer,
-	SEQUENCE_encode_xer,
-	SEQUENCE_decode_uper,
-	SEQUENCE_encode_uper,
-	SEQUENCE_decode_aper,
-	SEQUENCE_encode_aper,
-	0,	/* Use generic outmost tag fetcher */
 	asn_DEF_PDU_tags_1,
 	sizeof(asn_DEF_PDU_tags_1)
 		/sizeof(asn_DEF_PDU_tags_1[0]), /* 1 */
@@ -256,18 +246,8 @@
 asn_TYPE_descriptor_t asn_DEF_encoding_5 = {
 	"encoding",
 	"encoding",
-	CHOICE_free,
-	CHOICE_print,
+	&asn_OP_CHOICE,
 	CHOICE_constraint,
-	CHOICE_decode_ber,
-	CHOICE_encode_der,
-	CHOICE_decode_xer,
-	CHOICE_encode_xer,
-	CHOICE_decode_uper,
-	CHOICE_encode_uper,
-	CHOICE_decode_aper,
-	CHOICE_encode_aper,
-	CHOICE_outmost_tag,
 	0,	/* No effective tags (pointer) */
 	0,	/* No effective tags (count) */
 	0,	/* No tags (pointer) */
@@ -342,18 +322,8 @@
 asn_TYPE_descriptor_t asn_DEF_EXTERNAL = {
 	"EXTERNAL",
 	"EXTERNAL",
-	SEQUENCE_free,
-	SEQUENCE_print,
+	&asn_OP_SEQUENCE,
 	SEQUENCE_constraint,
-	SEQUENCE_decode_ber,
-	SEQUENCE_encode_der,
-	SEQUENCE_decode_xer,
-	SEQUENCE_encode_xer,
-	SEQUENCE_decode_uper,
-	SEQUENCE_encode_uper,
-	SEQUENCE_decode_aper,
-	SEQUENCE_encode_aper,
-	0,	/* Use generic outmost tag fetcher */
 	asn_DEF_EXTERNAL_tags_1,
 	sizeof(asn_DEF_EXTERNAL_tags_1)
 		/sizeof(asn_DEF_EXTERNAL_tags_1[0]) - 1, /* 1 */
. . . . .
Checking ../tests/97-type-identifier-SW.asn1 against ../tests/97-type-identifier-SW.asn1.-EF
WARNING: ASN.1 expression "TYPE-IDENTIFIER" at line 17 of module ASN1C-UsefulInformationObjectClasses
clashes with expression "TYPE-IDENTIFIER" at line 23 of module ModuleTypeIdentifier1 (../tests/97-type-identifier-SW.asn1).
Rename or remove either instance to resolve the conflict in ../skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1
Checking ../tests/98-attribute-class-OK.asn1 against ../tests/98-attribute-class-OK.asn1.-P
Checking ../tests/99-class-sample-OK.asn1 against ../tests/99-class-sample-OK.asn1.-EFprint-class-matrix
Error while processing ../tests/99-class-sample-OK.asn1.-EFprint-class-matrix (from ../tests/99-class-sample-OK.asn1)
FAIL check-parsing.sh (exit status: 1)
```

@velichkov if and when you have time - perhaps you could take a look at this.

**Comment by brchiu** [comment]
I could replace these `xxx.op->free_struct(....)` with ASN_STRUCT_FREE and ASN_STRUCT_FREE_CONTENTS_ONLY macro. Perhaps in a new PR since you merged this one.

**Comment by brchiu** [comment]
Please refer to PR #11.

**Comment by mouse07410** [comment]
Done. Thank you! Please enjoy the new master branch.

**Pull request merged**
