### PR TITLE
Generate code coverage report

### PR DESCRIPTION
**Pull request by velichkov**
The code coverage support seems to be lost in the current master so I've decided to add it again with some small improvements like branch coverage and `-fno-skeletons-copy` compiler flag.

I need the  `-fno-skeletons-copy` flag to improve the skeletons coverage report, by default the compiler copy the skeleton files and the gcov/lcov generate a separate report for each copy. Previously I've used another workaround by setting the -S to incorrect path but can't use this now because the asn1c can't find the EXTERNAL type definition

### CODE REVIEW

**Comment by velichkov** [comment]
@mouse07410 

We could build the code coverage reports in the Travis and send them to the https://coveralls.io/ or https://codecov.io. Both services are free for open source project and if you like them you just need to register with your github account and I'm going to add the needed scripts in the .travis.yml

Code coverage reports from the vlm repo -  https://coveralls.io/github/vlm/asn1c

**Comment by mouse07410** [comment]
Which one makes more sense? Or which one do you prefer? I'm happy to register there and enable Coverage.

**Comment by mouse07410** [comment]
@velichkov I'm adding COVERALLS (as you can see from the code). However I seem to have hit a rough patch (no pun intended :). If you see an obvious error in what I'm doing - please don't hesitate to drop me a note, here or elsewhere. I'd like to get Travis with Coveralls going ASAP.

**Comment by velichkov** [comment]
I'm also fighting with lcov and gcov. The versions in `precise` (the default linux container) are too old so now I'm trying the `trusty`.

I wanted to try codecov.io to compare it with coveralls.io

**Comment by velichkov** [comment]
it's working in `trusty`, hare is the first result
https://codecov.io/gh/velichkov/asn1c/tree/7f9ec75a2c288fd9ab9bc8ec0140c6ed4ee07ce5

I just need to fix the falling `distcheck`

**Comment by mouse07410** [comment]
Hmm... CI fails...?

I'm running CI on Trusty now (and on MacOS).

Take a look at what's going on there https://travis-ci.org/mouse07410/asn1c/builds/225849007 and tell me what's needed to get Coverage working. Or whether you think we should switch from COVERALLS to CODECOV. And/or just submit a PR doing that (I'll substitute the necessary security token if/when needed).

**Comment by velichkov** [comment]
Your Travis build succeed. I'll open a pull request for codecov once I'm done  (the codecov does not need the tokens)

**Comment by mouse07410** [comment]
It also needs to accommodate for Mac OSX: it looks like `-lgcov` fails there. (?)

**Pull request merged**
