### PR TITLE
Several APER encoding tests & fixes

### PR DESCRIPTION
**Pull request by pespin**

### CODE REVIEW

**Comment by laf0rge** [comment]
looks good to me, thanks!

**Comment by grzegorzniemirowski** [comment]
Please first read section 11.9 of X.691 which is about the length determinant. 11.5.7 applies to numbers generally.
aper_put_length() is implemented according to 11.9
aper_put_nsnnwn() is implemented according to 11.5.7

**Comment by acetcom** [comment]
@pespin 

I've tested your modification as below.

1. Copy your modification to the open5gs
```
$ git clone https://github.com/pespin/asn1c
$ cd asn1c
$ git checkout pespin/fix-aper
$ cd ..

$ git clone https://github.com/open5gs/open5gs
$ cd open5gs
$ cp ../asn1c/skeletons/aper_support.c lib/asn1c/common/aper_support.c 

```

2. Build open5gs
```
$ meson build --prefix=`pwd`/install
$ cd build
$ ninja
```

3. NGAP message test failed
```
$ ./tests/unit/unit ngap-message-test
ngap-message-test   : |Line 78: expected <0>, but saw <2>
|Line 110: expected <0>, but saw <2>
FAILED 2 of 4
Failed Tests   		Total	Fail	Failed %
===================================================
ngap-message-test		    4	   2	 50.00%

```

4. Other test also failed.
- EDIT test code as below.
```diff
$ diff --git a/tests/unit/ngap-message-test.c b/tests/unit/ngap-message-test.c
index 20179751d..99bcd131c 100644
--- a/tests/unit/ngap-message-test.c
+++ b/tests/unit/ngap-message-test.c
@@ -190,10 +190,14 @@ abts_suite *test_ngap_message(abts_suite *suite)
 
     ogs_log_install_domain(&__ogs_ngap_domain, "ngap", OGS_LOG_ERROR);
 
+#if 0
     abts_run_test(suite, ngap_message_test1, NULL);
+#endif
     abts_run_test(suite, ngap_message_test2, NULL);
+#if 0
     abts_run_test(suite, ngap_message_test3, NULL);
     abts_run_test(suite, ngap_message_test4, NULL);
+#endif
 
     return suite;
 }

```
- RUN tests
```
$ ninja
[1/2] Compiling C object 'tests/unit/3fcb9fe@@unit@exe/ngap-message-test.c.o'.
../tests/unit/ngap-message-test.c:152:13: warning: ‘ngap_message_test4’ defined but not used [-Wunused-function]
  152 | static void ngap_message_test4(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:117:13: warning: ‘ngap_message_test3’ defined but not used [-Wunused-function]
  117 | static void ngap_message_test3(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:23:13: warning: ‘ngap_message_test1’ defined but not used [-Wunused-function]
   23 | static void ngap_message_test1(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
[2/2] Linking target tests/unit/unit.

$ ./tests/unit/unit ngap-message-test
ngap-message-test   : |Line 110: expected <0>, but saw <2>
FAILED 1 of 1
Failed Tests   		Total	Fail	Failed %
===================================================
ngap-message-test		    1	   1	100.00%

```

5. Number 3 test is  succeeded
```
$ diff --git a/tests/unit/ngap-message-test.c b/tests/unit/ngap-message-test.c
index 20179751d..24a52f511 100644
--- a/tests/unit/ngap-message-test.c
+++ b/tests/unit/ngap-message-test.c
@@ -190,10 +190,14 @@ abts_suite *test_ngap_message(abts_suite *suite)
 
     ogs_log_install_domain(&__ogs_ngap_domain, "ngap", OGS_LOG_ERROR);
 
+#if 0
     abts_run_test(suite, ngap_message_test1, NULL);
     abts_run_test(suite, ngap_message_test2, NULL);
+#endif
     abts_run_test(suite, ngap_message_test3, NULL);
+#if 0
     abts_run_test(suite, ngap_message_test4, NULL);
+#endif
 
     return suite;

$ ninja
[1/2] Compiling C object 'tests/unit/3fcb9fe@@unit@exe/ngap-message-test.c.o'.
../tests/unit/ngap-message-test.c:152:13: warning: ‘ngap_message_test4’ defined but not used [-Wunused-function]
  152 | static void ngap_message_test4(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:85:13: warning: ‘ngap_message_test2’ defined but not used [-Wunused-function]
   85 | static void ngap_message_test2(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:23:13: warning: ‘ngap_message_test1’ defined but not used [-Wunused-function]
   23 | static void ngap_message_test1(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
[2/2] Linking target tests/unit/unit.

$ ./tests/unit/unit ngap-message-test
ngap-message-test   : SUCCESS
All tests passed.
```

6. Number 4 test is  succeeded
```
$ diff --git a/tests/unit/ngap-message-test.c b/tests/unit/ngap-message-test.c
index 20179751d..42a51b8f0 100644
--- a/tests/unit/ngap-message-test.c
+++ b/tests/unit/ngap-message-test.c
@@ -190,9 +190,11 @@ abts_suite *test_ngap_message(abts_suite *suite)
 
     ogs_log_install_domain(&__ogs_ngap_domain, "ngap", OGS_LOG_ERROR);
 
+#if 0
     abts_run_test(suite, ngap_message_test1, NULL);
     abts_run_test(suite, ngap_message_test2, NULL);
     abts_run_test(suite, ngap_message_test3, NULL);
+#endif
     abts_run_test(suite, ngap_message_test4, NULL);
 
     return suite;

$ ninja
[1/2] Compiling C object 'tests/unit/3fcb9fe@@unit@exe/ngap-message-test.c.o'.
../tests/unit/ngap-message-test.c:117:13: warning: ‘ngap_message_test3’ defined but not used [-Wunused-function]
  117 | static void ngap_message_test3(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:85:13: warning: ‘ngap_message_test2’ defined but not used [-Wunused-function]
   85 | static void ngap_message_test2(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~
../tests/unit/ngap-message-test.c:23:13: warning: ‘ngap_message_test1’ defined but not used [-Wunused-function]
   23 | static void ngap_message_test1(abts_case *tc, void *data)
      |             ^~~~~~~~~~~~~~~~~~

$ ./tests/unit/unit ngap-message-test
ngap-message-test   : SUCCESS
All tests passed.
```

So, I cannot merge your modification at this point.

Please feel free to ask for help at any time.

Thanks a lot!
Sukchan

**Comment by mouse07410** [comment]
While CI is running - anybody has any idea why NGAP seems to have a problem with length encoding that appears to conform to the X.691 standard?

**Comment by laf0rge** [comment]
> Please first read section 11.9 of X.691 which is about the length determinant. 11.5.7 applies to numbers generally. aper_put_length() is implemented according to 11.9 aper_put_nsnnwn() is implemented according to 11.5.7

thanks, you appear to have a valid point here.  This seems to get back to a misunderstanding between @pespin and myself, where he described an encoding problem which I assumed/understood to be about encoding a (contrained) integer value, while in fact it was about a length determinant. Sorry for that.

In any case, let's not close it right away and give everyone another day or so to think about it / play with it.  asn1c/vlm_master is generating wrong encoded APER output for SBcAP, based on our current anlysis. So something needs fixing, but it might have been fixed at the wrong part.

In any case, the APER INTEGER tests out of this PR should be merge-able; from what I can tell there seems to be quite some lack of APER test coverage compared to UPER or other encoding rules in general.

**Comment by grzegorzniemirowski** [comment]
So F1AP Reset decoding is broken again?

**Comment by mouse07410** [comment]
Probably, and let's continue discussion in #94. I really don't want to do that in already-merged PRs.

**Pull request merged**
