### PR TITLE
Add LTE-RRC example

### PR DESCRIPTION
**Pull request by brchiu**

### CODE REVIEW

**Comment by brchiu** [comment]
I don't know why the CI failed in :

```
(OK)  86.1 Compiler: clang C no environment variables set 6 min 5 sec
(FAIL) 86.2 Compiler: clang C BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64 3 min 22 sec
(FAIL) 86.3 Compiler: clang C BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32 6 min 59 sec
(FAIL) 86.4 Compiler: gcc C BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64 4 min 19 sec
(FAIL) 86.5 Compiler: gcc C BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32 4 min 17 sec
```

The last lines of failed CI logs are : 
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by mouse07410** [comment]
> I don't know why the CI failed...

I suspect it failed because the output is too verbose. That, compounded by the fact that RRC example is literally a *ton* of files, probably pushed the size of the log to beyond the Travis-allowed 4MB. At which point Travis aborted the run.

It looks like the test-run for MacOS produces less output, which is probably why the first test-run passed. And on Linux the output is more verbose - so all the four Linux runs failed.

Is there anything you can do to reduce the amount of output the example produces?

P.S. No, it did *not* look like "the test suite was rising the same exception over and over again".

**Comment by brchiu** [comment]
"Job log" screen can not show all log, you have to click the "Row log" button to show whole log file.

**Comment by brchiu** [comment]
I checked the config and found that you add 'make distcheck'. Perhaps it is the cause that so many logs generated.

**Comment by mouse07410** [comment]
> "Job log" screen can not show all log, you have to click the "Row log" button to show whole log file.

:-) I noticed. My response was based on observing the complete/raw log.

**Comment by velichkov** [comment]
Hi @brchiu 

One possible solution is to execute `make distcheck` instead of `make` and `make check` and `make dist check. I've already tested it and it pass successfully and the log file is ~3MB - see  fc279861d067f1c023dd40728bdfd4d0493dae51 and https://travis-ci.org/velichkov/asn1c/builds/224682021

**Comment by velichkov** [comment]
Other open source projects distribute the 36.331 ASN.1 files

- https://github.com/wireshark/wireshark/tree/master/epan/dissectors/asn1/lte-rrc
- https://github.com/mitshell/libmich/tree/master/libmich/asn1/asn/RRCLTE_36331-c10
- https://gitlab.eurecom.fr/oai/openairinterface5g/tree/master/openair2/RRC/LITE/MESSAGES/asn1c/ASN1_files

so maybe we could distribute them as well or at least we could add a Readme file with links to the standard and to these projects.

**Comment by brchiu** [comment]
@velichkov, 

Personally I would like to add 36.331 ASN.1 file here to let people test easier. And I know many open source projects already include them. But as I don't know why @vlm put a header in `rrc-7.1.0.asn1` that I am a little cautious to add this file into repository. 

```
 * DO NOT REDISTRIBUTE. Obtain your own copy of 3GPP RRC specification
 * if you need to create products based on this RRC ASN.1 module.
```
Of course for those 'not free' specification, for example SAE J735-201603, it is clearly not allowed to put in public. 

As for the large log file issue, currently I only know in @mouse07410 's  Travis CI environment, `stderr` was directed to `stdout`, so there were excessive output. However, I am not able to find out what setting or anything can make this difference. sigh...

**Comment by velichkov** [comment]
> However, I am not able to find out what setting or anything can make this difference. sigh...

Just apply fc27986  to your branch, it should be enough for now.

**Comment by velichkov** [comment]
Now we have a different problem

>/bin/bash: line 2: cd: /home/travis/build/mouse07410/asn1c/asn1c-1.0.0/_inst/share/asn1c: No such file or directory
>The command "DISTCHECK_CONFIGURE_FLAGS="-enable-Werror" make -j`nproc` distcheck" exited with 2.

And most probably the reason is that the parallel uninstall is borken

> DISTCHECK_CONFIGURE_FLAGS="-enable-Werror" make -j`nproc` distcheck

Try to remove the ```-j`nproc` ```

**Comment by brchiu** [comment]
Thank you @velichkov .

**Comment by mouse07410** [comment]
Makes sense... How sure are we that "make" and "make check" are being performed? Is there *any* record of that anywhere in the new log?

I'm all for shortening the log, but seeing those 39 "PASS..." lines did feel comforting. :-)

I'll check with Travis people to see if we can get an exception for a longer/larger log...

**Comment by brchiu** [comment]
Yes, agreed. I would rather like to know why these `stderr` log goes to output file, which will makes me more comforted.

However, I spent too longer time checking this, I'd like to move on other worthy topic. Like trying to find a way to solve name conflicting in different modules.

**Comment by mouse07410** [comment]
> However, I spent too longer time checking this, I'd like to move on other worthy topic. Like trying to find a way to solve name conflicting in different modules.

Understood. ;-)

**Pull request merged**
