### PR TITLE
Solve some problems found when processing S1AP, RANAP and J2735-201603

### PR DESCRIPTION
**Pull request by brchiu**
This pull request is a series of commit trying to fix some problems when I process S1AP, RANAP and DSRC.

Because [issue #147](https://github.com/vlm/asn1c/issues/147) has not been solved yet, I still have to slightly modify s1ap-14.2.0.asn1 and ranap-14.0.0.asn1 manually to circumvent it.

For example, 
```
RerouteNASRequestIEs RANAP-PROTOCOL-IES ::= {
	{ ID id-RANAP-Message		CRITICALITY ignore	TYPE OCTET STRING		PRESENCE mandatory}|
	{ ID id-SGSN-Group-Identity	CRITICALITY ignore	TYPE SGSN-Group-Identity	PRESENCE mandatory}|
	{ ID id-P-TMSI			CRITICALITY ignore	TYPE P-TMSI			PRESENCE optional}|
	{ ID id-UE-Usage-Type		CRITICALITY ignore	TYPE UE-Usage-Type		PRESENCE optional},
	...
}
```
was manually edited as 
```
RANAP-Message ::= OCTET STRING

RerouteNASRequestIEs RANAP-PROTOCOL-IES ::= {
	{ ID id-RANAP-Message		CRITICALITY ignore	TYPE RANAP-Message		PRESENCE mandatory}|
	{ ID id-SGSN-Group-Identity	CRITICALITY ignore	TYPE SGSN-Group-Identity	PRESENCE mandatory}|
	{ ID id-P-TMSI			CRITICALITY ignore	TYPE P-TMSI			PRESENCE optional}|
	{ ID id-UE-Usage-Type		CRITICALITY ignore	TYPE UE-Usage-Type		PRESENCE optional},
	...
}
```
And for S1AP,
```
S1-Message ::= OCTET STRING

RerouteNASRequest-IEs S1AP-PROTOCOL-IES ::= {
	{ ID id-eNB-UE-S1AP-ID		CRITICALITY reject	TYPE ENB-UE-S1AP-ID	PRESENCE mandatory}|
	{ ID id-MME-UE-S1AP-ID		CRITICALITY ignore	TYPE MME-UE-S1AP-ID	PRESENCE optional}|
	{ ID id-S1-Message		CRITICALITY reject	TYPE S1-Message		PRESENCE mandatory}|
	{ ID id-MME-Group-ID		CRITICALITY reject	TYPE MME-Group-ID	PRESENCE mandatory}|
	{ ID id-Additional-GUTI		CRITICALITY ignore	TYPE Additional-GUTI	PRESENCE optional}|
	{ ID id-UE-Usage-Type		CRITICALITY ignore	TYPE UE-Usage-Type	PRESENCE optional},
	...
}
```
After compiled `ranap-dump`, we can dump the content of sample RANAP message to first level :
```
./ranap-dump -iaper -oxer sample-RANAP-InitialUE-Message.aper

<RANAP-PDU>
    <initiatingMessage>
        <procedureCode>19</procedureCode>
        <criticality><ignore/></criticality>
        <value>
            00 00 06 00 03 40 01 00 00 0F 40 06 00 64 F0 90 
            18 07 00 3A 40 08 00 64 F0 90 18 07 00 01 00 10 
            40 11 10 05 24 71 03 00 00 00 08 49 06 90 08 40 
            08 87 72 00 4F 40 03 01 5D F4 00 56 40 05 64 F0 
            90 07 0F
        </value>
    </initiatingMessage>
</RANAP-PDU>
```

The aforementioned RANAP message comes from Wireshark's wiki. I don't have S1AP's sample message. I guess it also only decode to first level.
 
This work is not completed but it can serve as an beginning of further decoding the content inside value tag above. A more detail content decoding, like Wireshark did, is needed for real usage.

Then two examples : `examples/sample.source.S1AP` and `examples/sample.source.RANAP` are added.

As for J2735-201603 mentioned in [issue #121](https://github.com/vlm/asn1c/issues/121), this PR can solve grammar error and generates *.c/*.h files, but because duplicate names of internal types are heavily used in this ASN.1.  The generated *.c/*.h failed to compiled.

By the way, J2735-201603 is **not free** and I purchased it so I can legally use it, but I can not re-distribute it in this repository. 

-------
To summarized, there are incomplete works to do : 

1. [issue #147](https://github.com/vlm/asn1c/issues/147) or said the manipulation of class with syntax can be further elaborated, perhaps in a more elegant way instead of current asn1fix_cws.c implementation.

2. Further decoding/encoding of content inside RANAP and S1AP content shall be implemented.

3. To resolve conflict of duplicate type definition in *.c/*.h generated from J2735-201603, which might adding name mangling inside scope. 

4. I use an enumerate `TM_NAMECLASH` in [313ab1](https://github.com/brchiu/asn1c/commit/313ab1d7777095b87920dbb0f200fbadc4832914) to resolve duplication of type defined in different module. This name is not good for understanding. Any refinement of it is welcomed.

### CODE REVIEW

**Comment by mouse07410** [comment]
If memory serves, vlm/#147 (as you yourself described) pointed at two issues: (1) inability to handle field names with spaces, and (2) inability of `asn1f_lookup_symbol()` to handle basic types like `OCTET STRING`. Which of these two is this PR supposed to fix?

You mention partial fix for vlm/#121, and the fact that J2735-201603 is not free and therefore not re-distributable. Could you clarify - what exactly is not re-distributable? The standard itself? The code that handles/processes ASN.1 files compliant with that standard? The examples?

**Comment by brchiu** [comment]
1. None of both.
    The reason is even I modify `_asn1f_parse_class_object_data` to accept `OCTET STRING` by hard coded way to solve part 1, without solving part 2, we still have the following FATAL error message : 
```
FATAL: Cannot find OCTET STRING referenced by RerouteNASRequest-IEs at line xxx in ../s1ap-14.2.0.asn1
FATAL: Parsing ObjectSet RerouteNASRequest-IEs failed at xxx in ../s1ap-14.2.0.asn1
```
    
    So as stated in PR description, I circumvent this issue by modify S1AP and RANAP ASN.1 and move on working other issue when processing these two ASN.1.

2. I emphasize J2735-201603 that this specification and ASN.1 is not free because someone accidentally [asked for this file](https://sourceforge.net/p/asn1c/discussion/357921/thread/d8758a43/). It is to remind people who is interested in participating solving issue or testing about J2735-201603 not to breach.

**Comment by mouse07410** [comment]
I understand. 

I'm a little concerned of the hardcoding things like that. The objective is to keep the code clean...
Would appreciate a review. @velichkov, what's your take?

**Comment by brchiu** [comment]
Add 3 sample S1AP capture files in `examples/sample.source.S1AP` and squash into previous commit to make commit history cleaner.

Like RANAP case, `s1ap-dump -iaper -oxer sample-S1AP-InitialUEMessage.aper` only the first level is decoded.
```
<S1AP-PDU>
    <initiatingMessage>
        <procedureCode>12</procedureCode>
        <criticality><ignore/></criticality>
        <value>
            00 00 05 00 08 00 02 00 33 00 1A 00 2C 2B 07 41 
            72 0B F6 32 F5 49 80 00 01 00 00 00 01 04 E0 60 
            C0 C0 00 05 02 01 D0 11 D1 52 32 F5 49 00 3D 5C 
            20 00 90 11 03 57 18 86 F1 00 43 00 06 00 32 F5 
            49 00 3D 00 64 40 08 00 32 F5 49 00 00 10 00 00 
            86 40 01 30
        </value>
    </initiatingMessage>
</S1AP-PDU>
```

By the way, interestingly, I found that the codec generated by OAI also decoded to first level only. 
It seems decoding of ProtocolIE elements inside `value` field is done by additional written code rather by the automatic decoding mechanism embedded in asn1c itself.

So the item 2 in my previous summary, `Further decoding/encoding of content inside RANAP and S1AP content shall be implemented.` might be unnecessary, at least for usage scenario like OAI.  Of course it still be a nice feature if we can fully decode them like Wireshark did.

**Comment by brchiu** [comment]
Add fix of item 3 `To resolve conflict of duplicate type definition in .c/.h generated from J2735-201603, which might adding name mangling inside scope.`. C files generated from J2735-201603 can be compiled. 

ASN.1 parsing problems stated in [github issue #121](https://github.com/vlm/asn1c/issues/121) and  and subsequent compilation problem stated in [sourceforge bug #68](https://sourceforge.net/p/asn1c/bugs/68/) seems to be solved.

But I have no sample DSRC message at hand, so I am not able verify coder and decoder's correctness. Any people who works related to DSRC is welcomed to test it.

**Comment by mouse07410** [comment]
> ASN.1 parsing problems stated in github issue #121 and and subsequent compilation problem stated in sourceforge bug #68 seems to be solved.

My main concern is that this solution does not negatively impact other ASN.1 files and processing. While SAE J2735_201603 would be nice to handle - I wouldn't want it if the price for that is breaking or limiting something else.

**Comment by mouse07410** [comment]
After review, it looked like this PR should be merged.

**Pull request merged**
