### PR TITLE
JER (JSON Encoding Rules) Support

### PR DESCRIPTION
**Pull request by spfoos**
Creating a PR to start a discussion on how to proceed further. Any inputs welcome.

Currently, the scope is only encoding to JSON, not decoding from JSON. Not all types are supported.

make check fails.

TODO: Write tests. XER tests are weak, and only supports decoding tests.

### CODE REVIEW

**Comment by mouse07410** [comment]
@spfoos I really appreciate the effort to add JER support to ASN1C. But I can't merge a PR that doesn't pass the existing tests.

I realize this is a big effort, and requires time. Hopefully,as time goes,  you'll be able to make this PR more complete?

**Comment by mouse07410** [comment]
@spfoos could you please take a look at https://github.com/mouse07410/asn1c/runs/5337204846?check_suite_focus=true and consider fixing that? Thanks!

**Comment by spfoos** [comment]
@mouse07410 I have resolved all tests except 3.
2 in tests-c-compiler
1 in tests-randomize

I help trying to figure out the solution to these tests. It seems unrelated to the code changes I introduced (JER), whereas the tests are failing in XER and APER.

**Comment by spfoos** [comment]
@mouse07410 As you can see the checks are passing.  Can this PR be merged?

**Comment by mouse07410** [comment]
> As you can see the checks are passing. Can this PR be merged?

Good point. Merged, thank you!

A few questions about the direction this enhancement will take.

> Creating a PR to start a discussion on how to proceed further. Any inputs welcome.
> Currently, the scope is only encoding to JSON, not decoding from JSON. Not all types are supported.

Needless to say, I'd like to see JSON *decoding* as well. And, support of all allowed types.

Are you planning to work on that? I hope the answer is yes. ;-)

> make check fails.

Thankfully, not anymore. Good job!

> TODO: Write tests. XER tests are weak, and only supports decoding tests.

Yes. More tests would be welcome.

**Comment by mouse07410** [comment]
@spfoos any plans to continue JER implementation?

**Pull request merged**
