### PR TITLE
Add REAL constrain support. gh-148

### PR DESCRIPTION
**Pull request by velichkov**
When using converter-sample.c you need  to specify the `-c` flag

```
./progname -c -iaper -oxer Test2c.aper 
Test2c.aper: ASN.1 constraint check failed: REAL: constraint failed (Test2c.c:55)
```

```
./progname  -iaper -oxer Test2c.aper 
<Test2c>
    <count>41</count>
    <weight>0</weight>
    <data>
        26 EA 13 16 98 8E D2 ED 35 05 4B 77 08 D9 CD 13 
        00 A1 F7 76 32 E9 B1 BC 14 F9 83 BC 35 B4 D1 49 
        24 28 74 2B 59 DF 88 A8 50
    </data>
</Test2c>
```

### CODE REVIEW

**Comment by mouse07410** [comment]
**Thank you!!**

Constraints are recognized now for `REAL` (no pun intended :)).

I've a question. I have a test-program (somewhat similar to `converter-sample.c`) that encodes and decodes a Test2c PDU. And it behaves differently when INTEGER constraints fail compared to when REAL constraints fail:
```
. . . . .
Successfully BER-decoded Test2c_t PDU (51 bytes)
Failed to validate constraints! INTEGER: constraint failed (Test2c.c:30)
proceeding to see consequences...
Visual check:
<Test2c>
    <count>39</count>
    <weight>1.0</weight>
    <data>
        2C E1 57 DD D1 B2 D5 BD 9B 2F 49 C8 CC 8F BD 4E 
        43 FD 47 29 09 C0 F0 80 6F 0F 0F 28 15 6B 92 79 
        AE 49 53 A2 71 59 05
    </data>
</Test2c>

Failed to compute size for APER-encoded Test2c_t rc=-1
Failed to APER-encode Test2c_t PDU... (rc=-1)
. . . . .
```
vs.
```
Successfully BER-decoded Test2c_t PDU (50 bytes)
Failed to validate constraints! REAL: constraint failed (Test2c.c:61)
proceeding to see consequences...
Visual check:
<Test2c>
    <count>41</count>
    <weight>0</weight>
    <data>
        60 46 DE 76 0F 21 E2 E5 42 5D 10 1D 78 0B 51 8B 
        07 48 0E 53 B8 7A 87 31 1B 65 8D 3A AC 28 D3 30 
        3B C7 7E 03 63 57 41 E3 F6
    </data>
</Test2c>

Determined that APER-encoding of Test2c_t needs 368 bits = 46 bytes

Successfully APER-encoded Test2c_t PDU (46 bytes)
APER-encoded buffer in hex (for visual check):
30 30 02 01 29 09 00 04 29 60 46 de 76 0f 21 e2 
e5 42 5d 10 1d 78 0b 51 8b 07 48 0e 53 b8 7a 87 
31 1b 65 8d 3a ac 28 d3 30 3b c7 7e 03 63 57 41 
e3 f6 

Successfully APER-decoded Test2c_t PDU (46 bytes)
Failed to validate constraints! REAL: constraint failed (Test2c.c:61)
proceeding to see consequences...
Visual check:
<Test2c>
    <count>41</count>
    <weight>0</weight>
    <data>
        60 46 DE 76 0F 21 E2 E5 42 5D 10 1D 78 0B 51 8B 
        07 48 0E 53 B8 7A 87 31 1B 65 8D 3A AC 28 D3 30 
        3B C7 7E 03 63 57 41 E3 F6
    </data>
</Test2c>
```

I suspect that one of these exhibits incorrect behavior: either in the `INTEGER` case it should be able to determine the needed buffer size for the encoded PDU and/or successfully encode it, or in the `REAL` case it should fail to encode the PDU if the constraints are not satisfied.

What is your opinion?

**Comment by mouse07410** [comment]
And another problem: the current code does not detect/recognize the fractions, taking only the integer component of the `REAL` value of the constraints.

I've modified the ASN.1 test definition:
```
Test2c DEFINITIONS ::=
BEGIN

Test2c ::= SEQUENCE {

      count  INTEGER (40..20000),
      weight REAL (1.05 .. 21999.97),
      data   OCTET STRING SIZE (40..20000)
}

END
```

I'd expect the lower boundary in this case to be `1.05` rather than `2LL`. The generated code, however, uses `long long` values (file `Test2c.c`, lines 48-63):
```
        if(asn_REAL2double(st, &value)) {
                ASN__CTFAIL(app_key, td, sptr,
                        "%s: value too large (%s:%d)",
                        td->name, __FILE__, __LINE__);
                return -1;
        }

        if((value >= 2LL && value <= 21999LL)) {
                /* Constraint check succeeded */
                return 0;
        } else {
                ASN__CTFAIL(app_key, td, sptr,
                        "%s: constraint failed (%s:%d)",
                        td->name, __FILE__, __LINE__);
                return -1;
        }
```

**Comment by velichkov** [comment]
> I've a question. I have a test-program (somewhat similar to converter-sample.c) that encodes and decodes a Test2c PDU. And it behaves differently when INTEGER constraints fail compared to when REAL constraints fail:
> ....
> I suspect that one of these exhibits incorrect behavior: either in the INTEGER case it should be able to determine the needed buffer size for the encoded PDU and/or successfully encode it, or in the REAL case it should fail to encode the PDU if the constraints are not satisfied.

It turns out that in PER there are two types of constraints - PER-visible and not PER-visible.

From X.691

>3.7.22 PER-visible constraint: An instance of use of the ASN.1 constraint notation which **affects the PER encoding of a value**.
>
> 10.3.14 Constraints applied to **real types are not PER-visible**.
> 10.3.18 Subject to the above, all other constraints **are PER-visible if and only if they are applied to an integer type** or to a known-multiplier character string type.

So the reason why PER encode fails with INTEGER but succeed with REAL is that the REAL constraints are not PER=visible (i.e. do not affect PER encoding). This behavior will be similar for other types that have non PER-visible constraints and also for other encodings, I guess that DER/XER encode of this PDU will succeed.

> And another problem: the current code does not detect/recognize the fractions, taking only the integer component of the REAL value of the constraints.
> I'd expect the lower boundary in this case to be 1.05 rather than 2LL, likewise for the upper boundary. The generated code, however, uses long long values (file Test2c.c, lines 48-63):

I'll try to fix this

**Comment by mouse07410** [comment]
> It turns out that in PER there are two types of constraints - PER-visible and not PER-visible. ... From X.691

Ha! I see it would have been helpful for me to check with X.691 first. :-)

Thank you for clarifying this issue.

> ...I guess that DER/XER encode of this PDU will succeed.

Yes, you're 100% correct - both DER and XER encoded that PDU correctly too, despite constraints not being satisfied.

> > ...the current code does not detect/recognize the fractions, taking only the integer component of the REAL value of the constraints.
>
> I'll try to fix this

Perfect, thanks!!

P.S. I'm trying to add OSX to the Travis CI builds. Not much luck so far. :-(

**Pull request merged**
